<a href="https://colab.research.google.com/github/joseluisspindola/ExtraccionDeDatos/blob/main/Actividad2_2/Actividad2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df= pd.read_csv("listings.csv")
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,40669,https://www.airbnb.com/rooms/40669,20250317171123,2025-03-18,city scrape,Skyy’s Lounge / Cozyaezz so,NaN,The neighborhood is very diverse & friendly sh...,https://a0.muscache.com/pictures/af7e4a45-0118...,175412,...,4.86,4.90,4.95,Exempt,f,1,0,1,0,0.12
1,215768,https://www.airbnb.com/rooms/215768,20250317171123,2025-03-18,city scrape,Minutes to Manhattan & Jersey Shore,Walking to distance to Statue of Liberty and E...,"Such close proximity to NYC, 7 minutes on the ...",https://a0.muscache.com/pictures/miso/Hosting-...,846837,...,4.89,4.38,4.80,STR-006450-2024,f,2,2,0,0,1.26
2,254245,https://www.airbnb.com/rooms/254245,20250317171123,2025-03-18,city scrape,Minutes to Manhattan and NJ Shore,Walking distance to Statue of Liberty and Elli...,"Such close proximity to NYC, 7 minutes on the ...",https://a0.muscache.com/pictures/hosting/Hosti...,846837,...,4.85,4.40,4.74,STR-006336-2024,f,2,2,0,0,0.92
3,269266,https://www.airbnb.com/rooms/269266,20250317171123,2025-03-18,city scrape,Modern private 2 bedrooms apt minutes to NYC,Enjoy that private luxury two bedrooms apartme...,Our House is located in the Liberty State Park...,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.67,3.89,4.46,STR-001785-2025,t,10,1,9,0,2.91
4,271255,https://www.airbnb.com/rooms/271255,20250317171123,2025-03-18,city scrape,Large Room with private bathroom min to Manhattan,You can enjoy your stay in large bedroom with ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.62,3.89,4.43,STR-001786-2025,t,10,1,9,0,2.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1772,1374179859570440739,https://www.airbnb.com/rooms/1374179859570440739,20250317171123,2025-03-18,city scrape,Modern Cozy Studio Apt In JC,MODERN Cozy Jersey City Studio Apt : Modern C...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,191233734,...,NaN,NaN,NaN,Exempt,f,1,1,0,0,NaN
1773,1374213532871546161,https://www.airbnb.com/rooms/1374213532871546161,20250317171123,2025-03-18,city scrape,Manhattan Apt in JC/NYC,Bring the whole family to this great place wit...,NaN,https://a0.muscache.com/pictures/d8053e54-4ccf...,91382887,...,NaN,NaN,NaN,Str-012193-2024,t,6,6,0,0,NaN
1774,1374572542533199411,https://www.airbnb.com/rooms/1374572542533199411,20250317171123,2025-03-18,city scrape,Classy Condo w Rooftop NYC Views,The whole group will enjoy easy access to ever...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,508414175,...,NaN,NaN,NaN,STR-002813-2025,f,7,7,0,0,NaN
1775,1377755184862184574,https://www.airbnb.com/rooms/1377755184862184574,20250317171123,2025-03-18,city scrape,Modern New 1BR1BA minutes to NYC,Take a break and unwind at this peaceful oasis.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,404408603,...,NaN,NaN,NaN,Exempt,t,8,8,0,0,NaN
1776,1378115987432045942,https://www.airbnb.com/rooms/1378115987432045942,20250317171123,2025-03-18,city scrape,Modern & Cozy 5 Bedroom Home,"This modern 5-bedroom home offers a spacious, ...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,473437724,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [ ]:
#5 host names diferentes
filtro1=df[(df["host_name"] == "Skyy") | (df["host_name"] == "Magdalena") | (df["host_name"] == "Laura") | (df["host_name"] == "Colby") | (df["host_name"] == "Edward")]
filtro1

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,40669,https://www.airbnb.com/rooms/40669,20250317171123,2025-03-18,city scrape,Skyy’s Lounge / Cozyaezz so,NaN,The neighborhood is very diverse & friendly sh...,https://a0.muscache.com/pictures/af7e4a45-0118...,175412,...,4.86,4.90,4.95,Exempt,f,1,0,1,0,0.12
3,269266,https://www.airbnb.com/rooms/269266,20250317171123,2025-03-18,city scrape,Modern private 2 bedrooms apt minutes to NYC,Enjoy that private luxury two bedrooms apartme...,Our House is located in the Liberty State Park...,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.67,3.89,4.46,STR-001785-2025,t,10,1,9,0,2.91
4,271255,https://www.airbnb.com/rooms/271255,20250317171123,2025-03-18,city scrape,Large Room with private bathroom min to Manhattan,You can enjoy your stay in large bedroom with ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.62,3.89,4.43,STR-001786-2025,t,10,1,9,0,2.49
6,810860,https://www.airbnb.com/rooms/810860,20250317171123,2025-03-18,city scrape,Spacious Studio minutes away from NYC,Spacious Studio loft apartment on the ground f...,"The neighborhood is seconds from ""Little India...",https://a0.muscache.com/pictures/miso/Hosting-...,3530754,...,5.00,4.63,4.63,NaN,f,1,1,0,0,0.11
12,1280528,https://www.airbnb.com/rooms/1280528,20250317171123,2025-03-19,previous scrape,Fantastic room with private bathroom close NYC!,Enjoy this great bedroom with private bathroom...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.67,3.90,4.47,STR-001786-2025,t,10,1,9,0,2.25
16,2149271,https://www.airbnb.com/rooms/2149271,20250317171123,2025-03-18,city scrape,"DWTN Jersey City Art Studio Apt, long term stays",Art studio apt. in downtown Jersey City. Comp...,"Jersey City is exploding with new restaurants,...",https://a0.muscache.com/pictures/35bf1fd5-ba83...,10969148,...,4.77,4.77,4.73,NaN,f,1,1,0,0,0.30
21,2662979,https://www.airbnb.com/rooms/2662979,20250317171123,2025-03-18,city scrape,Room with private bathroom min to Manhattan,Enjoy beautiful bedroom with en suite bathroom...,Our Downtown neighborhood is the best place to...,https://a0.muscache.com/pictures/34874281/6085...,1410590,...,4.69,4.53,4.63,NaN,t,10,1,9,0,2.80
23,3193538,https://www.airbnb.com/rooms/3193538,20250317171123,2025-03-18,city scrape,Lrg Garden Studio w/Yard Min 30 Night Corp Rental,This is a large 2-room fully furnished studio ...,The Paulus Hook Historic District of Jersey Ci...,https://a0.muscache.com/pictures/hosting/Hosti...,16186604,...,4.95,4.90,4.89,NaN,f,1,1,0,0,1.91
126,17994898,https://www.airbnb.com/rooms/17994898,20250317171123,2025-03-18,city scrape,Beautiful room with private bathroom and garden.,Feel welcome in a private bedroom with your ow...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.75,4.11,4.53,STR-001786-2025,t,10,1,9,0,2.76
359,45550425,https://www.airbnb.com/rooms/45550425,20250317171123,2025-03-19,previous scrape,"Family-Friendly, 3Bed/2bath, huge yard, parking","Welcome to our cozy 3-bedroom, 2-bath family h...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,4581902,...,5.00,4.75,5.00,NaN,f,1,1,0,0,0.27
414,50264726,https://www.airbnb.com/rooms/50264726,20250317171123,2025-03-18,city scrape,Cheerful and affordable bedroom close to NYC,This unique place has a style all its own. Enj...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,5.00,4.33,4.22,NaN,t,10,1,9,0,0.32
419,50348478,https://www.airbnb.com/rooms/50348478,20250317171123,2025-03-18,city scrape,Sunny and private bedroom close to NYC!,Sunny and large bedroom with big closets. The ...,NaN,https://a0.muscache.com/pictures/1e42af5e-ffe6...,1410590,...,4.70,4.50,4.40,NaN,t,10,1,9,0,0.24
540,639909158764273212,https://www.airbnb.com/rooms/639909158764273212,20250317171123,2025-03-18,city scrape,Great bedroom - shared bathroom and patio near...,Great bedroom with the comfortable queen size...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.89,4.22,4.44,NaN,t,10,1,9,0,0.35
541,639909334619822556,https://www.airbnb.com/rooms/639909334619822556,20250317171123,2025-03-18,city scrape,Unique bedroom in great area close to NYC.,This unique place has a style all its own.,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.78,3.78,4.67,NaN,t,10,1,9,0,0.28
611,733512322709221071,https://www.airbnb.com/rooms/733512322709221071,20250317171123,2025-03-18,city scrape,Large bedroom close to Manhatta,This unique place has a style all its own. You...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,5.00,4.50,4.75,NaN,t,10,1,9,0,0.20

In [ ]:
filtro1["host_name"].head(10)

0           Skyy
3      Magdalena
4      Magdalena
6          Laura
12     Magdalena
16         Colby
21     Magdalena
23        Edward
126    Magdalena
359    Magdalena
Name: host_name, dtype: object

In [ ]:
filtro1.to_csv("EjercicioA.csv")

In [ ]:
#5 hosts que se unieron después de 2020
filtro2=df[df["host_since"] >= "2021-01-01"]
filtro2

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
240,31038685,https://www.airbnb.com/rooms/31038685,20250317171123,2025-03-18,city scrape,829-2AL Private Bedroom 25 to NYC Time Square,This is a bedroom in a 2nd floor 5 bedroom 2 b...,"Jersey City Heights, ""The Heights"" is a family...",https://a0.muscache.com/pictures/edefa73f-c24f...,443343607,...,4.74,4.70,4.52,NaN,f,43,2,41,0,0.36
330,41438439,https://www.airbnb.com/rooms/41438439,20250317171123,2025-03-18,city scrape,829-1AL Private Bedroom 25 mins to NYC Time Sq...,"Private, clean, quiet bedroom /2 full beds for...",Jersey Heights area and Union City downtown is...,https://a0.muscache.com/pictures/e6d67446-d307...,443343607,...,4.87,4.47,4.47,NaN,f,43,2,41,0,0.24
386,47951280,https://www.airbnb.com/rooms/47951280,20250317171123,2025-03-18,city scrape,Contemporary Brownstone - Luxury Treat!,This two-family brownstone is nestled on a bea...,NaN,https://a0.muscache.com/pictures/a013c900-484c...,386489995,...,5.00,4.58,4.77,NaN,f,2,2,0,0,0.52
387,47953186,https://www.airbnb.com/rooms/47953186,20250317171123,2025-03-18,city scrape,Cozy Apartment 25 Mins to NYC,This two-family brownstone is nestled on a bea...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,386489995,...,5.00,4.19,4.67,STR-2024-00015,t,2,2,0,0,1.13
394,48488222,https://www.airbnb.com/rooms/48488222,20250317171123,2025-03-18,city scrape,15 mins Drive to NYC| Vintage House + Backyard,This vintage rustic modern decorated house bri...,This space is located in the Bergen-Lafayette ...,https://a0.muscache.com/pictures/miso/Hosting-...,391042686,...,4.77,4.00,4.35,STR-004442-2024,f,2,2,0,0,1.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1768,1371071551203567741,https://www.airbnb.com/rooms/1371071551203567741,20250317171123,2025-03-18,city scrape,Ultimate Family Escape – 7BR w/ Comfort&Style ...,Immerse yourself into luxury at our meticulous...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,557857185,...,NaN,NaN,NaN,STR-006349-2025,f,7,7,0,0,NaN
1771,1374126253489868990,https://www.airbnb.com/rooms/1374126253489868990,20250317171123,2025-03-18,city scrape,Luxury Retreat| Walk 2 PATH| NYC in Mins | Par...,"Step into a beautifully designed, spacious 3-b...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,670405055,...,NaN,NaN,NaN,STR-005925-2024,f,1,1,0,0,NaN
1774,1374572542533199411,https://www.airbnb.com/rooms/1374572542533199411,20250317171123,2025-03-18,city scrape,Classy Condo w Rooftop NYC Views,The whole group will enjoy easy access to ever...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,508414175,...,NaN,NaN,NaN,STR-002813-2025,f,7,7,0,0,NaN
1775,1377755184862184574,https://www.airbnb.com/rooms/1377755184862184574,20250317171123,2025-03-18,city scrape,Modern New 1BR1BA minutes to NYC,Take a break and unwind at this peaceful oasis.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,404408603,...,NaN,NaN,NaN,Exempt,t,8,8,0,0,NaN
1776,1378115987432045942,https://www.airbnb.com/rooms/1378115987432045942,20250317171123,2025-03-18,city scrape,Modern & Cozy 5 Bedroom Home,"This modern 5-bedroom home offers a spacious, ...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,473437724,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [ ]:
filtro2["host_since"].head()

240    2022-02-03
330    2022-02-03
386    2021-01-29
387    2021-01-29
394    2021-03-03
Name: host_since, dtype: object

In [ ]:
filtro2.to_csv("EjercicioB.csv")

In [ ]:
#Responden a más tardar en 1 día
filtro3=df[(df["host_response_time"] == "within an hour") | (df["host_response_time"] == "within a few hours") | (df["host_response_time"] == "within a day")]
filtro3

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
1,215768,https://www.airbnb.com/rooms/215768,20250317171123,2025-03-18,city scrape,Minutes to Manhattan & Jersey Shore,Walking to distance to Statue of Liberty and E...,"Such close proximity to NYC, 7 minutes on the ...",https://a0.muscache.com/pictures/miso/Hosting-...,846837,...,4.89,4.38,4.80,STR-006450-2024,f,2,2,0,0,1.26
2,254245,https://www.airbnb.com/rooms/254245,20250317171123,2025-03-18,city scrape,Minutes to Manhattan and NJ Shore,Walking distance to Statue of Liberty and Elli...,"Such close proximity to NYC, 7 minutes on the ...",https://a0.muscache.com/pictures/hosting/Hosti...,846837,...,4.85,4.40,4.74,STR-006336-2024,f,2,2,0,0,0.92
3,269266,https://www.airbnb.com/rooms/269266,20250317171123,2025-03-18,city scrape,Modern private 2 bedrooms apt minutes to NYC,Enjoy that private luxury two bedrooms apartme...,Our House is located in the Liberty State Park...,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.67,3.89,4.46,STR-001785-2025,t,10,1,9,0,2.91
4,271255,https://www.airbnb.com/rooms/271255,20250317171123,2025-03-18,city scrape,Large Room with private bathroom min to Manhattan,You can enjoy your stay in large bedroom with ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.62,3.89,4.43,STR-001786-2025,t,10,1,9,0,2.49
5,675483,https://www.airbnb.com/rooms/675483,20250317171123,2025-03-18,city scrape,Room & Private Bath~Minutes to NYC!,Full disclosure - professional photographs mak...,Downtown Jersey City is right outside of Manha...,https://a0.muscache.com/pictures/miso/Hosting-...,2259684,...,4.94,4.83,4.76,STR-006162-2024,f,1,0,1,0,2.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1771,1374126253489868990,https://www.airbnb.com/rooms/1374126253489868990,20250317171123,2025-03-18,city scrape,Luxury Retreat| Walk 2 PATH| NYC in Mins | Par...,"Step into a beautifully designed, spacious 3-b...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,670405055,...,NaN,NaN,NaN,STR-005925-2024,f,1,1,0,0,NaN
1772,1374179859570440739,https://www.airbnb.com/rooms/1374179859570440739,20250317171123,2025-03-18,city scrape,Modern Cozy Studio Apt In JC,MODERN Cozy Jersey City Studio Apt : Modern C...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,191233734,...,NaN,NaN,NaN,Exempt,f,1,1,0,0,NaN
1773,1374213532871546161,https://www.airbnb.com/rooms/1374213532871546161,20250317171123,2025-03-18,city scrape,Manhattan Apt in JC/NYC,Bring the whole family to this great place wit...,NaN,https://a0.muscache.com/pictures/d8053e54-4ccf...,91382887,...,NaN,NaN,NaN,Str-012193-2024,t,6,6,0,0,NaN
1774,1374572542533199411,https://www.airbnb.com/rooms/1374572542533199411,20250317171123,2025-03-18,city scrape,Classy Condo w Rooftop NYC Views,The whole group will enjoy easy access to ever...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,508414175,...,NaN,NaN,NaN,STR-002813-2025,f,7,7,0,0,NaN
1775,1377755184862184574,https://www.airbnb.com/rooms/1377755184862184574,20250317171123,2025-03-18,city scrape,Modern New 1BR1BA minutes to NYC,Take a break and unwind at this peaceful oasis.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,404408603,...,NaN,NaN,NaN,Exempt,t,8,8,0,0,NaN

In [ ]:
df["host_response_time"].head()

0               NaN
1    within an hour
2    within an hour
3    within an hour
4    within an hour
Name: host_response_time, dtype: object

In [ ]:
filtro3.to_csv("EjercicioC.csv")

In [ ]:
#Multiplos de 200
filtro4=df.iloc[200::200, :]
filtro4

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
200,26199055,https://www.airbnb.com/rooms/26199055,20250317171123,2025-03-19,city scrape,"72 ""3"" Huge Bright room by Iight rail/Bus/WIFI",Bright and very spacious private room with a q...,The neighborhood has experienced a revitalizat...,https://a0.muscache.com/pictures/eb4358dc-c4ee...,6958867,...,4.80,4.02,4.54,Exempt,f,35,5,30,0,0.56
400,49052823,https://www.airbnb.com/rooms/49052823,20250317171123,2025-03-18,city scrape,Comfortable Room for Longterm Stay* Easy Parking*,"Spacious, light-filled room with a big closet ...","Just across the river from Manhattan, Jersey C...",https://a0.muscache.com/pictures/e13457f4-4139...,274604030,...,5.00,4.00,3.00,NaN,f,17,2,15,0,0.12
600,724486979887953737,https://www.airbnb.com/rooms/724486979887953737,20250317171123,2025-03-19,previous scrape,Lovely Room in Jersey City for Longterm Stay,"Comfortable, cozy, and clean room with a big c...","Just across the river from Manhattan, Jersey C...",https://a0.muscache.com/pictures/miso/Hosting-...,295287039,...,NaN,NaN,NaN,NaN,f,5,0,5,0,NaN
800,930689968515770160,https://www.airbnb.com/rooms/930689968515770160,20250317171123,2025-03-18,city scrape,RetroRevive - Newly Renovated 2 Bed 1 Bath!,Welcome to RetroRevive - a thoughtfully curate...,Nestled in the up-and-coming urban neighborhoo...,https://a0.muscache.com/pictures/63b61403-0ce5...,28783771,...,4.97,4.43,4.70,STR-005921-2024,f,6,6,0,0,3.30
1000,1047783538010552081,https://www.airbnb.com/rooms/1047783538010552081,20250317171123,2025-03-18,city scrape,~Modern Luxe City Vibe Gem A,Enjoy a stylish experience at this centrally l...,Bergen Lafayette is a diverse and historic nei...,https://a0.muscache.com/pictures/miso/Hosting-...,549010681,...,4.56,3.71,4.15,STR-101237-2025,f,14,0,14,0,2.30
1200,1153122130403965097,https://www.airbnb.com/rooms/1153122130403965097,20250317171123,2025-03-18,city scrape,Charming Private 4 Bedrm Apt walk to train to NYC,Discover comfort and convenience in our privat...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,536849530,...,5.00,5.00,5.00,Exempt,f,28,7,21,0,1.00
1400,1226307485262569784,https://www.airbnb.com/rooms/1226307485262569784,20250317171123,2025-03-18,city scrape,O&L Luxury Rental,O&L Luxury Rentals is a beautiful lower level ...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,596987324,...,4.83,4.50,4.67,NaN,f,1,1,0,0,1.82
1600,1308375945980068076,https://www.airbnb.com/rooms/1308375945980068076,20250317171123,2025-03-18,city scrape,Stylish Jersey City 3BR | Near PATH to NYC,"Welcome to this freshly renovated 3-bedroom, 2...",This area blends the charm of old-world browns...,https://a0.muscache.com/pictures/hosting/Hosti...,666093686,...,4.89,4.67,4.78,STR-778391-2024,f,2,2,0,0,2.87

In [ ]:
filtro4.to_csv("EjercicioD.csv")

In [ ]:
#Entire home y private rooom
filtro5=df[(df["room_type"] == "Entire home/apt") | (df["room_type"] == "Private room")]
filtro5

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,40669,https://www.airbnb.com/rooms/40669,20250317171123,2025-03-18,city scrape,Skyy’s Lounge / Cozyaezz so,NaN,The neighborhood is very diverse & friendly sh...,https://a0.muscache.com/pictures/af7e4a45-0118...,175412,...,4.86,4.90,4.95,Exempt,f,1,0,1,0,0.12
1,215768,https://www.airbnb.com/rooms/215768,20250317171123,2025-03-18,city scrape,Minutes to Manhattan & Jersey Shore,Walking to distance to Statue of Liberty and E...,"Such close proximity to NYC, 7 minutes on the ...",https://a0.muscache.com/pictures/miso/Hosting-...,846837,...,4.89,4.38,4.80,STR-006450-2024,f,2,2,0,0,1.26
2,254245,https://www.airbnb.com/rooms/254245,20250317171123,2025-03-18,city scrape,Minutes to Manhattan and NJ Shore,Walking distance to Statue of Liberty and Elli...,"Such close proximity to NYC, 7 minutes on the ...",https://a0.muscache.com/pictures/hosting/Hosti...,846837,...,4.85,4.40,4.74,STR-006336-2024,f,2,2,0,0,0.92
3,269266,https://www.airbnb.com/rooms/269266,20250317171123,2025-03-18,city scrape,Modern private 2 bedrooms apt minutes to NYC,Enjoy that private luxury two bedrooms apartme...,Our House is located in the Liberty State Park...,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.67,3.89,4.46,STR-001785-2025,t,10,1,9,0,2.91
4,271255,https://www.airbnb.com/rooms/271255,20250317171123,2025-03-18,city scrape,Large Room with private bathroom min to Manhattan,You can enjoy your stay in large bedroom with ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.62,3.89,4.43,STR-001786-2025,t,10,1,9,0,2.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1772,1374179859570440739,https://www.airbnb.com/rooms/1374179859570440739,20250317171123,2025-03-18,city scrape,Modern Cozy Studio Apt In JC,MODERN Cozy Jersey City Studio Apt : Modern C...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,191233734,...,NaN,NaN,NaN,Exempt,f,1,1,0,0,NaN
1773,1374213532871546161,https://www.airbnb.com/rooms/1374213532871546161,20250317171123,2025-03-18,city scrape,Manhattan Apt in JC/NYC,Bring the whole family to this great place wit...,NaN,https://a0.muscache.com/pictures/d8053e54-4ccf...,91382887,...,NaN,NaN,NaN,Str-012193-2024,t,6,6,0,0,NaN
1774,1374572542533199411,https://www.airbnb.com/rooms/1374572542533199411,20250317171123,2025-03-18,city scrape,Classy Condo w Rooftop NYC Views,The whole group will enjoy easy access to ever...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,508414175,...,NaN,NaN,NaN,STR-002813-2025,f,7,7,0,0,NaN
1775,1377755184862184574,https://www.airbnb.com/rooms/1377755184862184574,20250317171123,2025-03-18,city scrape,Modern New 1BR1BA minutes to NYC,Take a break and unwind at this peaceful oasis.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,404408603,...,NaN,NaN,NaN,Exempt,t,8,8,0,0,NaN
1776,1378115987432045942,https://www.airbnb.com/rooms/1378115987432045942,20250317171123,2025-03-18,city scrape,Modern & Cozy 5 Bedroom Home,"This modern 5-bedroom home offers a spacious, ...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,473437724,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN

In [ ]:
filtro5["room_type"]

0          Private room
1       Entire home/apt
2       Entire home/apt
3       Entire home/apt
4          Private room
             ...
1772    Entire home/apt
1773    Entire home/apt
1774    Entire home/apt
1775    Entire home/apt
1776    Entire home/apt
Name: room_type, Length: 1765, dtype: object

In [ ]:
filtro5.to_csv("EjercicioE.csv")

In [ ]:
#Que tengan maximo 4 camas
filtro6=df[df["beds"] <= 4]
filtro6

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,40669,https://www.airbnb.com/rooms/40669,20250317171123,2025-03-18,city scrape,Skyy’s Lounge / Cozyaezz so,NaN,The neighborhood is very diverse & friendly sh...,https://a0.muscache.com/pictures/af7e4a45-0118...,175412,...,4.86,4.90,4.95,Exempt,f,1,0,1,0,0.12
1,215768,https://www.airbnb.com/rooms/215768,20250317171123,2025-03-18,city scrape,Minutes to Manhattan & Jersey Shore,Walking to distance to Statue of Liberty and E...,"Such close proximity to NYC, 7 minutes on the ...",https://a0.muscache.com/pictures/miso/Hosting-...,846837,...,4.89,4.38,4.80,STR-006450-2024,f,2,2,0,0,1.26
2,254245,https://www.airbnb.com/rooms/254245,20250317171123,2025-03-18,city scrape,Minutes to Manhattan and NJ Shore,Walking distance to Statue of Liberty and Elli...,"Such close proximity to NYC, 7 minutes on the ...",https://a0.muscache.com/pictures/hosting/Hosti...,846837,...,4.85,4.40,4.74,STR-006336-2024,f,2,2,0,0,0.92
3,269266,https://www.airbnb.com/rooms/269266,20250317171123,2025-03-18,city scrape,Modern private 2 bedrooms apt minutes to NYC,Enjoy that private luxury two bedrooms apartme...,Our House is located in the Liberty State Park...,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.67,3.89,4.46,STR-001785-2025,t,10,1,9,0,2.91
4,271255,https://www.airbnb.com/rooms/271255,20250317171123,2025-03-18,city scrape,Large Room with private bathroom min to Manhattan,You can enjoy your stay in large bedroom with ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1410590,...,4.62,3.89,4.43,STR-001786-2025,t,10,1,9,0,2.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1771,1374126253489868990,https://www.airbnb.com/rooms/1374126253489868990,20250317171123,2025-03-18,city scrape,Luxury Retreat| Walk 2 PATH| NYC in Mins | Par...,"Step into a beautifully designed, spacious 3-b...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,670405055,...,NaN,NaN,NaN,STR-005925-2024,f,1,1,0,0,NaN
1772,1374179859570440739,https://www.airbnb.com/rooms/1374179859570440739,20250317171123,2025-03-18,city scrape,Modern Cozy Studio Apt In JC,MODERN Cozy Jersey City Studio Apt : Modern C...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,191233734,...,NaN,NaN,NaN,Exempt,f,1,1,0,0,NaN
1773,1374213532871546161,https://www.airbnb.com/rooms/1374213532871546161,20250317171123,2025-03-18,city scrape,Manhattan Apt in JC/NYC,Bring the whole family to this great place wit...,NaN,https://a0.muscache.com/pictures/d8053e54-4ccf...,91382887,...,NaN,NaN,NaN,Str-012193-2024,t,6,6,0,0,NaN
1774,1374572542533199411,https://www.airbnb.com/rooms/1374572542533199411,20250317171123,2025-03-18,city scrape,Classy Condo w Rooftop NYC Views,The whole group will enjoy easy access to ever...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,508414175,...,NaN,NaN,NaN,STR-002813-2025,f,7,7,0,0,NaN
1775,1377755184862184574,https://www.airbnb.com/rooms/1377755184862184574,20250317171123,2025-03-18,city scrape,Modern New 1BR1BA minutes to NYC,Take a break and unwind at this peaceful oasis.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,404408603,...,NaN,NaN,NaN,Exempt,t,8,8,0,0,NaN

In [ ]:
filtro6["beds"]

0       1.0
1       2.0
2       1.0
3       3.0
4       3.0
       ...
1771    4.0
1772    1.0
1773    4.0
1774    2.0
1775    2.0
Name: beds, Length: 1415, dtype: float64

In [ ]:
filtro6.to_csv("EjercicioF.csv")

In [ ]:
#Es superhost
filtro7=df[df["host_is_superhost"] == "t"]
filtro7

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
1,215768,https://www.airbnb.com/rooms/215768,20250317171123,2025-03-18,city scrape,Minutes to Manhattan & Jersey Shore,Walking to distance to Statue of Liberty and E...,"Such close proximity to NYC, 7 minutes on the ...",https://a0.muscache.com/pictures/miso/Hosting-...,846837,...,4.89,4.38,4.80,STR-006450-2024,f,2,2,0,0,1.26
2,254245,https://www.airbnb.com/rooms/254245,20250317171123,2025-03-18,city scrape,Minutes to Manhattan and NJ Shore,Walking distance to Statue of Liberty and Elli...,"Such close proximity to NYC, 7 minutes on the ...",https://a0.muscache.com/pictures/hosting/Hosti...,846837,...,4.85,4.40,4.74,STR-006336-2024,f,2,2,0,0,0.92
6,810860,https://www.airbnb.com/rooms/810860,20250317171123,2025-03-18,city scrape,Spacious Studio minutes away from NYC,Spacious Studio loft apartment on the ground f...,"The neighborhood is seconds from ""Little India...",https://a0.muscache.com/pictures/miso/Hosting-...,3530754,...,5.00,4.63,4.63,NaN,f,1,1,0,0,0.11
7,818075,https://www.airbnb.com/rooms/818075,20250317171123,2025-03-18,city scrape,Lovely Apartment - Easy access to NYC,Our guests tell us that they love coming back ...,Our area of Jersey City Heights is quiet and s...,https://a0.muscache.com/pictures/hosting/Hosti...,4296829,...,4.97,4.69,4.93,STR-005916-2024,f,1,1,0,0,1.41
10,971427,https://www.airbnb.com/rooms/971427,20250317171123,2025-03-19,previous scrape,Nice Apt -10 minutes to Manhattan,"Large apartment in Downtown Jersey City, steps...",Mercer Street is in the heart of Historic Down...,https://a0.muscache.com/pictures/14556984/0f70...,4318265,...,4.90,4.85,4.80,str-006261-2024,f,2,2,0,0,2.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1767,1371059856010195011,https://www.airbnb.com/rooms/1371059856010195011,20250317171123,2025-03-18,city scrape,Stylish & Spacious Stay Near NYC 3BR/2BATH,Step into opulence at our thoughtfully crafted...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,557857185,...,NaN,NaN,NaN,STR-006349-2025,f,7,7,0,0,NaN
1768,1371071551203567741,https://www.airbnb.com/rooms/1371071551203567741,20250317171123,2025-03-18,city scrape,Ultimate Family Escape – 7BR w/ Comfort&Style ...,Immerse yourself into luxury at our meticulous...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,557857185,...,NaN,NaN,NaN,STR-006349-2025,f,7,7,0,0,NaN
1773,1374213532871546161,https://www.airbnb.com/rooms/1374213532871546161,20250317171123,2025-03-18,city scrape,Manhattan Apt in JC/NYC,Bring the whole family to this great place wit...,NaN,https://a0.muscache.com/pictures/d8053e54-4ccf...,91382887,...,NaN,NaN,NaN,Str-012193-2024,t,6,6,0,0,NaN
1774,1374572542533199411,https://www.airbnb.com/rooms/1374572542533199411,20250317171123,2025-03-18,city scrape,Classy Condo w Rooftop NYC Views,The whole group will enjoy easy access to ever...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,508414175,...,NaN,NaN,NaN,STR-002813-2025,f,7,7,0,0,NaN
1775,1377755184862184574,https://www.airbnb.com/rooms/1377755184862184574,20250317171123,2025-03-18,city scrape,Modern New 1BR1BA minutes to NYC,Take a break and unwind at this peaceful oasis.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,404408603,...,NaN,NaN,NaN,Exempt,t,8,8,0,0,NaN

In [ ]:
filtro7["host_is_superhost"]

1       t
2       t
6       t
7       t
10      t
       ..
1767    t
1768    t
1773    t
1774    t
1775    t
Name: host_is_superhost, Length: 677, dtype: object

In [ ]:
filtro7.to_csv("EjercicioG.csv")

In [ ]:
#Columnas impares
filtro8 =df.iloc[:, 1::2]
filtro8

,listing_url,last_scraped,name,neighborhood_overview,host_id,host_name,host_location,host_response_time,host_acceptance_rate,host_thumbnail_url,...,availability_eoy,estimated_occupancy_l365d,first_review,review_scores_rating,review_scores_cleanliness,review_scores_communication,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_shared_rooms
0,https://www.airbnb.com/rooms/40669,2025-03-18,Skyy’s Lounge / Cozyaezz so,The neighborhood is very diverse & friendly sh...,175412,Skyy,"Jersey City, NJ",NaN,100%,https://a0.muscache.com/im/users/175412/profil...,...,83,50,2010-09-23,4.95,4.95,4.86,4.95,f,0,0
1,https://www.airbnb.com/rooms/215768,2025-03-18,Minutes to Manhattan & Jersey Shore,"Such close proximity to NYC, 7 minutes on the ...",846837,Charlaine,"Jersey City, NJ",within an hour,98%,https://a0.muscache.com/im/pictures/user/User-...,...,241,255,2011-09-13,4.81,4.91,4.89,4.80,f,2,0
2,https://www.airbnb.com/rooms/254245,2025-03-18,Minutes to Manhattan and NJ Shore,"Such close proximity to NYC, 7 minutes on the ...",846837,Charlaine,"Jersey City, NJ",within an hour,98%,https://a0.muscache.com/im/pictures/user/User-...,...,272,175,2011-11-21,4.76,4.90,4.85,4.74,f,2,0
3,https://www.airbnb.com/rooms/269266,2025-03-18,Modern private 2 bedrooms apt minutes to NYC,Our House is located in the Liberty State Park...,1410590,Magdalena,"Jersey City, NJ",within an hour,99%,https://a0.muscache.com/im/users/1410590/profi...,...,220,255,2011-11-25,4.38,4.55,4.67,4.46,t,1,0
4,https://www.airbnb.com/rooms/271255,2025-03-18,Large Room with private bathroom min to Manhattan,NaN,1410590,Magdalena,"Jersey City, NJ",within an hour,99%,https://a0.muscache.com/im/users/1410590/profi...,...,112,230,2012-04-16,4.45,4.69,4.62,4.43,t,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1772,https://www.airbnb.com/rooms/1374179859570440739,2025-03-18,Modern Cozy Studio Apt In JC,NaN,191233734,Shenee,"New York, United States",within an hour,100%,https://a0.muscache.com/im/pictures/user/323ac...,...,156,0,NaN,NaN,NaN,NaN,NaN,f,1,0
1773,https://www.airbnb.com/rooms/1374213532871546161,2025-03-18,Manhattan Apt in JC/NYC,NaN,91382887,Daniel,"New York, NY",within an hour,98%,https://a0.muscache.com/im/pictures/user/1c8c9...,...,65,0,NaN,NaN,NaN,NaN,NaN,t,6,0
1774,https://www.airbnb.com/rooms/1374572542533199411,2025-03-18,Classy Condo w Rooftop NYC Views,NaN,508414175,Mahdi,"Jersey City, NJ",within an hour,100%,https://a0.muscache.com/im/pictures/user/User/...,...,271,0,NaN,NaN,NaN,NaN,NaN,f,7,0
1775,https://www.airbnb.com/rooms/1377755184862184574,2025-03-18,Modern New 1BR1BA minutes to NYC,NaN,404408603,Surender,"North Brunswick Township, NJ",within an hour,94%,https://a0.muscache.com/im/pictures/user/User-...,...,156,0,NaN,NaN,NaN,NaN,NaN,t,8,0
1776,https://www.airbnb.com/rooms/1378115987432045942,2025-03-18,Modern & Cozy 5 Bedroom Home,NaN,473437724,Sudahna,NaN,NaN,NaN,https://a0.muscache.com/im/pictures/user/bdb0b...,...,289,0,NaN,NaN,NaN,NaN,NaN,f,1,0

In [ ]:
filtro8.to_csv("EjercicioH.csv")

In [ ]:
#Referencia
#Get the Data. (s.f.). Inside Airbnb. https://insideairbnb.com/get-the-data/